#
# This is a working example of using GitHub Actions to publish the docs
# to the GitHub Pages (gh_pages) branch.
#
# Remember to have a requirements.txt file with the required dependencies.
#
name: Deploy Site

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**'
    branches:
    - development
    #
    # If your repository would have releases should you uncomment the below lines
    # in order to ignore pushes caused by newly created releases.
    #tags-ignore:
    #- '**'

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Deploy Files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add site
        git commit -m "Update Website (${GITHUB_SHA:0:7})"
        git push master origin
