name: "Update robots.txt"

on:
    schedule:
      - cron: '0 12 * * 0'
    workflow_dispatch:

jobs:
  updateRobotsFile:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5
        with:
          path: source
      - name: "Checkout ai.robots.txt Repository"
        run: "git clone https://github.com/ai-robots-txt/ai.robots.txt remote"
      - name: "Generate App Access token"
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
      - name: "Update file if different"
        run: |
          if git diff --no-index --exit-code "source/site/robots.txt" "remote/robots.txt"; then
            echo "No difference found. Skipping..."
          else
            echo "Difference found. Updating file..."
            cp "remote/robots.txt" "source/site/robots.txt"
            cd source
            git config --global user.email "11576465+Andre601@users.noreply.github.com"
            git config --global user.name "Andre601's Bot"
            git remote set-url origin https://${{ steps.generate-token.outputs.token }}@github.com/Andre601/andre601.github.io
            git add site/robots.txt
            git commit -m "Update robots.txt from ai.robots.txt"
            git push
            echo "Update complete!"
          fi
